import type {
  Activity,
  Booking,
  BudgetBreakdown,
  CityInfo,
  Collaborator,
  Hotel,
  Itinerary,
  ItineraryDay,
  ItinerarySlot,
  TravelEvent,
  TripStats,
  WeatherDay,
} from "@/types";

interface PopularDestination {
  name: string;
  country: string;
  avgBudget: number;
  bestMonths: string;
  flightHoursFromIndia: number;
  coverImage: string;
}

const unsplash = (id: string) => `https://images.unsplash.com/${id}?w=800&q=80`;

const createSlot = (period: ItinerarySlot["period"], items: ItinerarySlot["items"]): ItinerarySlot => ({
  period,
  items,
});

export const goaCollaborators: Collaborator[] = [
  {
    id: "col-1",
    userId: "usr-101",
    name: "Aarav Mehta",
    avatar: "https://ui-avatars.com/api/?name=Aarav+Mehta&background=6366F1&color=fff",
    role: "owner",
    isOnline: true,
    lastSeen: new Date("2026-03-12T10:15:00.000Z"),
  },
  {
    id: "col-2",
    userId: "usr-102",
    name: "Mira Kapoor",
    avatar: "https://ui-avatars.com/api/?name=Mira+Kapoor&background=0EA5E9&color=fff",
    role: "editor",
    isOnline: true,
    lastSeen: new Date("2026-03-12T10:18:00.000Z"),
  },
  {
    id: "col-3",
    userId: "usr-103",
    name: "Dev Nair",
    avatar: "https://ui-avatars.com/api/?name=Dev+Nair&background=10B981&color=fff",
    role: "editor",
    isOnline: false,
    lastSeen: new Date("2026-03-11T19:05:00.000Z"),
  },
  {
    id: "col-4",
    userId: "usr-104",
    name: "Sana Iqbal",
    avatar: "https://ui-avatars.com/api/?name=Sana+Iqbal&background=F59E0B&color=fff",
    role: "viewer",
    isOnline: false,
    lastSeen: new Date("2026-03-10T15:32:00.000Z"),
  },
];

export const goaHotels: Hotel[] = [
  {
    id: "goa-h-1",
    name: "Anjuna Palm Retreat",
    city: "Goa",
    country: "India",
    pricePerNight: 3200,
    currency: "INR",
    rating: 4.2,
    stars: 3,
    images: [unsplash("photo-1519046904884-53103b34b206")],
    amenities: ["Free WiFi", "Beach Access", "Breakfast", "Airport Shuttle"],
    lat: 15.5759,
    lng: 73.7396,
    description: "A cozy boutique stay close to Anjuna beach and local cafes.",
    externalId: "amd-hotel-anjuna-palm-retreat",
  },
  {
    id: "goa-h-2",
    name: "Baga Bay Residency",
    city: "Goa",
    country: "India",
    pricePerNight: 4500,
    currency: "INR",
    rating: 4.1,
    stars: 3,
    images: [unsplash("photo-1566073771259-6a8506099945")],
    amenities: ["Pool", "Breakfast", "Parking", "WiFi"],
    lat: 15.5553,
    lng: 73.7517,
    description: "Comfortable rooms and walking distance from nightlife in Baga.",
    externalId: "amd-hotel-baga-bay-residency",
  },
  {
    id: "goa-h-3",
    name: "Candolim Courtyard Suites",
    city: "Goa",
    country: "India",
    pricePerNight: 6900,
    currency: "INR",
    rating: 4.4,
    stars: 4,
    images: [unsplash("photo-1551882547-ff40c63fe5fa")],
    amenities: ["Pool", "Gym", "Spa", "Concierge"],
    lat: 15.5152,
    lng: 73.7681,
    description: "Family-friendly upscale property near Candolim beachfront.",
    externalId: "amd-hotel-candolim-courtyard-suites",
  },
  {
    id: "goa-h-4",
    name: "Palolem Cove Cottages",
    city: "Goa",
    country: "India",
    pricePerNight: 2800,
    currency: "INR",
    rating: 4.0,
    stars: 3,
    images: [unsplash("photo-1522708323590-d24dbb6b0267")],
    amenities: ["Beachfront", "Restaurant", "Bike Rental", "WiFi"],
    lat: 15.0098,
    lng: 74.0232,
    description: "Rustic-chic cottages ideal for relaxed South Goa stays.",
    externalId: "amd-hotel-palolem-cove-cottages",
  },
  {
    id: "goa-h-5",
    name: "Siolim Riverfront Villa",
    city: "Goa",
    country: "India",
    pricePerNight: 9800,
    currency: "INR",
    rating: 4.6,
    stars: 4,
    images: [unsplash("photo-1468824357306-a439d58ccb1c")],
    amenities: ["Private Pool", "Kitchen", "River View", "Chef on Request"],
    lat: 15.6139,
    lng: 73.7678,
    description: "Elegant villa stay with river views and premium privacy.",
    externalId: "amd-hotel-siolim-riverfront-villa",
  },
  {
    id: "goa-h-6",
    name: "Morjim Dune Boutique",
    city: "Goa",
    country: "India",
    pricePerNight: 7600,
    currency: "INR",
    rating: 4.5,
    stars: 4,
    images: [unsplash("photo-1505693416388-ac5ce068fe85")],
    amenities: ["Infinity Pool", "Bar", "Yoga Deck", "WiFi"],
    lat: 15.6318,
    lng: 73.7394,
    description: "Modern boutique resort near Morjim and Ashwem beaches.",
    externalId: "amd-hotel-morjim-dune-boutique",
  },
  {
    id: "goa-h-7",
    name: "Taj Fort Aguada Resort & Spa",
    city: "Goa",
    country: "India",
    pricePerNight: 21000,
    currency: "INR",
    rating: 4.8,
    stars: 5,
    images: [unsplash("photo-1445019980597-93fa8acb246c")],
    amenities: ["Private Beach", "Luxury Spa", "Fine Dining", "Kids Club"],
    lat: 15.4937,
    lng: 73.7732,
    description: "Iconic luxury resort overlooking the Arabian Sea.",
    externalId: "amd-hotel-taj-fort-aguada",
  },
  {
    id: "goa-h-8",
    name: "Alila Diwa Goa",
    city: "Goa",
    country: "India",
    pricePerNight: 25000,
    currency: "INR",
    rating: 4.9,
    stars: 5,
    images: [unsplash("photo-1571896349842-33c89424de2d")],
    amenities: ["Lagoon Pool", "Butler Service", "Luxury Spa", "Airport Transfer"],
    lat: 15.2742,
    lng: 73.9137,
    description: "Luxury escape in South Goa with premium experiences.",
    externalId: "amd-hotel-alila-diwa-goa",
  },
];

export const goaActivities: Activity[] = [
  {
    id: "goa-a-1",
    name: "Baga Beach Chill Walk",
    city: "Goa",
    category: "beach",
    price: 0,
    currency: "INR",
    duration: 90,
    rating: 4.5,
    image: unsplash("photo-1507525428034-b723cf961d3e"),
    description: "Morning beach stroll with cafes and water views at Baga.",
    lat: 15.5568,
    lng: 73.7517,
    openingHours: "06:00-20:00",
    externalId: "otm-baga-beach",
  },
  {
    id: "goa-a-2",
    name: "Anjuna Beach Sunset Session",
    city: "Goa",
    category: "beach",
    price: 200,
    currency: "INR",
    duration: 120,
    rating: 4.6,
    image: unsplash("photo-1518509562904-e7ef99cdcc86"),
    description: "Evening beach vibe with live music and flea market buzz.",
    lat: 15.5772,
    lng: 73.7396,
    openingHours: "08:00-22:00",
    externalId: "otm-anjuna-beach",
  },
  {
    id: "goa-a-3",
    name: "Palolem Beach Kayaking",
    city: "Goa",
    category: "beach",
    price: 900,
    currency: "INR",
    duration: 90,
    rating: 4.7,
    image: unsplash("photo-1483683804023-6ccdb62f86ef"),
    description: "Guided kayaking near the serene Palolem coastline.",
    lat: 15.0096,
    lng: 74.0232,
    openingHours: "07:00-18:30",
    externalId: "otm-palolem-kayak",
  },
  {
    id: "goa-a-4",
    name: "Gunpowder Seafood Lunch",
    city: "Goa",
    category: "restaurant",
    price: 1400,
    currency: "INR",
    duration: 75,
    rating: 4.4,
    image: unsplash("photo-1517248135467-4c7edcad34c4"),
    description: "Popular coastal-style seafood spot known for bold flavors.",
    lat: 15.5932,
    lng: 73.747,
    openingHours: "12:00-23:00",
    externalId: "otm-gunpowder-goa",
  },
  {
    id: "goa-a-5",
    name: "Thalassa Rooftop Dinner",
    city: "Goa",
    category: "restaurant",
    price: 2200,
    currency: "INR",
    duration: 120,
    rating: 4.5,
    image: unsplash("photo-1414235077428-338989a2e8c0"),
    description: "Sunset dining and Mediterranean menu with sea views.",
    lat: 15.6155,
    lng: 73.7577,
    openingHours: "18:00-00:00",
    externalId: "otm-thalassa-goa",
  },
  {
    id: "goa-a-6",
    name: "Candolim Jet Ski Ride",
    city: "Goa",
    category: "adventure",
    price: 1200,
    currency: "INR",
    duration: 30,
    rating: 4.3,
    image: unsplash("photo-1521336575822-6da63fb45455"),
    description: "High-speed jet ski session with safety gear included.",
    lat: 15.5148,
    lng: 73.7622,
    openingHours: "09:00-17:30",
    externalId: "otm-candolim-jetski",
  },
  {
    id: "goa-a-7",
    name: "Calangute Parasailing",
    city: "Goa",
    category: "adventure",
    price: 1800,
    currency: "INR",
    duration: 45,
    rating: 4.4,
    image: unsplash("photo-1533240332313-0db49b459ad6"),
    description: "Aerial parasailing with sweeping views of North Goa.",
    lat: 15.5439,
    lng: 73.7553,
    openingHours: "10:00-17:00",
    externalId: "otm-calangute-parasail",
  },
  {
    id: "goa-a-8",
    name: "Goa Spice Plantation Tour",
    city: "Goa",
    category: "nature",
    price: 1100,
    currency: "INR",
    duration: 150,
    rating: 4.6,
    image: unsplash("photo-1472396961693-142e6e269027"),
    description: "Guided walk through traditional spice farms with lunch.",
    lat: 15.4133,
    lng: 74.0147,
    openingHours: "09:30-16:00",
    externalId: "otm-goa-spice-farm",
  },
  {
    id: "goa-a-9",
    name: "Mandovi Sunset Cruise",
    city: "Goa",
    category: "culture",
    price: 850,
    currency: "INR",
    duration: 90,
    rating: 4.2,
    image: unsplash("photo-1473116763249-2faaef81ccda"),
    description: "River cruise with live music, dance, and skyline views.",
    lat: 15.4989,
    lng: 73.8291,
    openingHours: "17:00-19:30",
    externalId: "otm-mandovi-cruise",
  },
  {
    id: "goa-a-10",
    name: "Basilica of Bom Jesus Visit",
    city: "Goa",
    category: "museum",
    price: 0,
    currency: "INR",
    duration: 60,
    rating: 4.7,
    image: unsplash("photo-1524492412937-b28074a5d7da"),
    description: "UNESCO church landmark in Old Goa with historic interiors.",
    lat: 15.5009,
    lng: 73.9115,
    openingHours: "09:00-18:30",
    externalId: "otm-bom-jesus",
  },
  {
    id: "goa-a-11",
    name: "Se Cathedral Heritage Walk",
    city: "Goa",
    category: "culture",
    price: 300,
    currency: "INR",
    duration: 75,
    rating: 4.5,
    image: unsplash("photo-1539650116574-75c0c6d73f88"),
    description: "Guided walk through Se Cathedral and old Portuguese quarter.",
    lat: 15.5036,
    lng: 73.9127,
    openingHours: "10:00-17:00",
    externalId: "otm-se-cathedral",
  },
  {
    id: "goa-a-12",
    name: "Arpora Saturday Night Market",
    city: "Goa",
    category: "shopping",
    price: 500,
    currency: "INR",
    duration: 120,
    rating: 4.4,
    image: unsplash("photo-1481437156560-3205f6a55735"),
    description: "Night bazaar with local crafts, global food, and live acts.",
    lat: 15.5658,
    lng: 73.7643,
    openingHours: "18:00-23:30",
    externalId: "otm-arpora-market",
  },
  {
    id: "goa-a-13",
    name: "Silent Noise Beach Party",
    city: "Goa",
    category: "nightlife",
    price: 1500,
    currency: "INR",
    duration: 180,
    rating: 4.3,
    image: unsplash("photo-1492684223066-81342ee5ff30"),
    description: "Famous headphone party experience by the shoreline.",
    lat: 15.538,
    lng: 73.7612,
    openingHours: "20:00-02:00",
    externalId: "otm-silent-noise-party",
  },
  {
    id: "goa-a-14",
    name: "Ashwem Yoga & Wellness Session",
    city: "Goa",
    category: "wellness",
    price: 1200,
    currency: "INR",
    duration: 90,
    rating: 4.8,
    image: unsplash("photo-1506126613408-eca07ce68773"),
    description: "Sunrise yoga class with guided breathwork by the beach.",
    lat: 15.6375,
    lng: 73.7359,
    openingHours: "06:00-08:00",
    externalId: "otm-ashwem-yoga",
  },
  {
    id: "goa-a-15",
    name: "Dudhsagar Jeep Adventure",
    city: "Goa",
    category: "adventure",
    price: 2400,
    currency: "INR",
    duration: 300,
    rating: 4.6,
    image: unsplash("photo-1501785888041-af3ef285b470"),
    description: "Jeep safari and waterfall trek to iconic Dudhsagar falls.",
    lat: 15.3144,
    lng: 74.314,
    openingHours: "07:00-16:00",
    externalId: "otm-dudhsagar-jeep",
  },
];

export const goaEvents: TravelEvent[] = [
  {
    id: "goa-e-1",
    name: "Sunburn Festival Goa",
    city: "Goa",
    date: "2026-12-28",
    price: 4500,
    currency: "INR",
    venue: "Vagator Hilltop Grounds",
    image: unsplash("photo-1459749411175-04bf5292ceea"),
    description: "Major electronic music festival with international DJs.",
    category: "Music",
    url: "https://www.sunburn.in/",
  },
  {
    id: "goa-e-2",
    name: "Goa Carnival Parade",
    city: "Goa",
    date: "2026-02-14",
    price: 0,
    currency: "INR",
    venue: "Panaji City Center",
    image: unsplash("photo-1504199367641-aba8151af406"),
    description: "Colorful parade with floats, dance troupes, and street food.",
    category: "Cultural",
    url: "https://www.goa-tourism.com/events/goa-carnival/",
  },
  {
    id: "goa-e-3",
    name: "Anjuna Full Moon Beach Party",
    city: "Goa",
    date: "2026-01-17",
    price: 1800,
    currency: "INR",
    venue: "Anjuna Shoreline Stage",
    image: unsplash("photo-1470229538611-16ba8c7ffbd7"),
    description: "Late-night beach party with indie and house acts.",
    category: "Nightlife",
    url: "https://www.eventbrite.com/",
  },
  {
    id: "goa-e-4",
    name: "Fontainhas Heritage Walk & Fado Night",
    city: "Goa",
    date: "2026-01-19",
    price: 1200,
    currency: "INR",
    venue: "Fontainhas Latin Quarter",
    image: unsplash("photo-1467269204594-9661b134dd2b"),
    description: "Guided heritage walk followed by Portuguese-inspired music.",
    category: "Cultural",
    url: "https://www.eventbrite.com/",
  },
  {
    id: "goa-e-5",
    name: "Goa Food & Craft Weekend",
    city: "Goa",
    date: "2026-01-21",
    price: 700,
    currency: "INR",
    venue: "Saligao Grounds",
    image: unsplash("photo-1559339352-11d035aa65de"),
    description: "Weekend fair featuring Goan cuisine, crafts, and live sets.",
    category: "Food",
    url: "https://www.eventbrite.com/",
  },
];

export const goaWeatherForecast: WeatherDay[] = [
  {
    date: "2026-01-16",
    tempMax: 31,
    tempMin: 24,
    condition: "Sunny",
    precipitationChance: 5,
    windSpeed: 14,
    icon: "sun",
  },
  {
    date: "2026-01-17",
    tempMax: 32,
    tempMin: 25,
    condition: "Mostly Sunny",
    precipitationChance: 8,
    windSpeed: 16,
    icon: "sun",
  },
  {
    date: "2026-01-18",
    tempMax: 30,
    tempMin: 24,
    condition: "Partly Cloudy",
    precipitationChance: 12,
    windSpeed: 13,
    icon: "cloud-sun",
  },
  {
    date: "2026-01-19",
    tempMax: 29,
    tempMin: 23,
    condition: "Sunny",
    precipitationChance: 10,
    windSpeed: 12,
    icon: "sun",
  },
  {
    date: "2026-01-20",
    tempMax: 31,
    tempMin: 24,
    condition: "Clear",
    precipitationChance: 6,
    windSpeed: 11,
    icon: "sun",
  },
];

const goaItineraryDays: ItineraryDay[] = [
  {
    dayNumber: 1,
    date: "2026-01-16",
    weather: goaWeatherForecast[0],
    slots: [
      createSlot("morning", [
        {
          id: "goa-d1-i1",
          type: "activity",
          itemId: goaActivities[0].id,
          data: goaActivities[0],
          startTime: "08:00",
          endTime: "09:30",
          estimatedCost: 0,
          currency: "INR",
          orderIndex: 1,
        },
      ]),
      createSlot("afternoon", [
        {
          id: "goa-d1-i2",
          type: "activity",
          itemId: goaActivities[3].id,
          data: goaActivities[3],
          startTime: "13:00",
          endTime: "14:15",
          estimatedCost: 1400,
          currency: "INR",
          orderIndex: 2,
        },
      ]),
      createSlot("evening", [
        {
          id: "goa-d1-i3",
          type: "event",
          itemId: goaEvents[2].id,
          data: goaEvents[2],
          startTime: "20:30",
          endTime: "23:30",
          estimatedCost: 1800,
          currency: "INR",
          orderIndex: 3,
        },
      ]),
    ],
    hotel: goaHotels[2],
    totalCost: 3200 + 1400 + 1800,
    route: [
      {
        from: "Candolim Courtyard Suites",
        to: "Baga Beach",
        distanceKm: 6.5,
        durationMinutes: 18,
        mode: "driving",
      },
      {
        from: "Baga Beach",
        to: "Anjuna Shoreline Stage",
        distanceKm: 7.4,
        durationMinutes: 21,
        mode: "driving",
      },
    ],
  },
  {
    dayNumber: 2,
    date: "2026-01-17",
    weather: goaWeatherForecast[1],
    slots: [
      createSlot("morning", [
        {
          id: "goa-d2-i1",
          type: "activity",
          itemId: goaActivities[6].id,
          data: goaActivities[6],
          startTime: "10:00",
          endTime: "10:45",
          estimatedCost: 1800,
          currency: "INR",
          orderIndex: 1,
        },
      ]),
      createSlot("afternoon", [
        {
          id: "goa-d2-i2",
          type: "activity",
          itemId: goaActivities[8].id,
          data: goaActivities[8],
          startTime: "17:00",
          endTime: "18:30",
          estimatedCost: 850,
          currency: "INR",
          orderIndex: 2,
        },
      ]),
      createSlot("evening", [
        {
          id: "goa-d2-i3",
          type: "activity",
          itemId: goaActivities[4].id,
          data: goaActivities[4],
          startTime: "19:30",
          endTime: "21:30",
          estimatedCost: 2200,
          currency: "INR",
          orderIndex: 3,
        },
      ]),
    ],
    hotel: goaHotels[2],
    totalCost: 3200 + 1800 + 850 + 2200,
    route: [
      {
        from: "Candolim Courtyard Suites",
        to: "Calangute Beach",
        distanceKm: 4.3,
        durationMinutes: 15,
        mode: "driving",
      },
      {
        from: "Calangute Beach",
        to: "Mandovi Jetty",
        distanceKm: 12.8,
        durationMinutes: 32,
        mode: "driving",
      },
    ],
  },
  {
    dayNumber: 3,
    date: "2026-01-18",
    weather: goaWeatherForecast[2],
    slots: [
      createSlot("morning", [
        {
          id: "goa-d3-i1",
          type: "activity",
          itemId: goaActivities[9].id,
          data: goaActivities[9],
          startTime: "09:30",
          endTime: "10:30",
          estimatedCost: 0,
          currency: "INR",
          orderIndex: 1,
        },
      ]),
      createSlot("afternoon", [
        {
          id: "goa-d3-i2",
          type: "activity",
          itemId: goaActivities[10].id,
          data: goaActivities[10],
          startTime: "12:00",
          endTime: "13:15",
          estimatedCost: 300,
          currency: "INR",
          orderIndex: 2,
        },
      ]),
      createSlot("evening", [
        {
          id: "goa-d3-i3",
          type: "event",
          itemId: goaEvents[3].id,
          data: goaEvents[3],
          startTime: "18:00",
          endTime: "20:00",
          estimatedCost: 1200,
          currency: "INR",
          orderIndex: 3,
        },
      ]),
    ],
    hotel: goaHotels[5],
    totalCost: 7600 + 300 + 1200,
    route: [
      {
        from: "Morjim Dune Boutique",
        to: "Old Goa Churches",
        distanceKm: 28.1,
        durationMinutes: 54,
        mode: "driving",
      },
      {
        from: "Old Goa Churches",
        to: "Fontainhas",
        distanceKm: 10.2,
        durationMinutes: 24,
        mode: "driving",
      },
    ],
  },
  {
    dayNumber: 4,
    date: "2026-01-19",
    weather: goaWeatherForecast[3],
    slots: [
      createSlot("morning", [
        {
          id: "goa-d4-i1",
          type: "activity",
          itemId: goaActivities[7].id,
          data: goaActivities[7],
          startTime: "10:00",
          endTime: "12:30",
          estimatedCost: 1100,
          currency: "INR",
          orderIndex: 1,
        },
      ]),
      createSlot("afternoon", [
        {
          id: "goa-d4-i2",
          type: "activity",
          itemId: goaActivities[11].id,
          data: goaActivities[11],
          startTime: "16:30",
          endTime: "18:30",
          estimatedCost: 500,
          currency: "INR",
          orderIndex: 2,
        },
      ]),
      createSlot("evening", [
        {
          id: "goa-d4-i3",
          type: "event",
          itemId: goaEvents[4].id,
          data: goaEvents[4],
          startTime: "19:00",
          endTime: "21:30",
          estimatedCost: 700,
          currency: "INR",
          orderIndex: 3,
        },
      ]),
    ],
    hotel: goaHotels[5],
    totalCost: 7600 + 1100 + 500 + 700,
    route: [
      {
        from: "Morjim Dune Boutique",
        to: "Ponda Spice Plantation",
        distanceKm: 41.3,
        durationMinutes: 75,
        mode: "driving",
      },
      {
        from: "Ponda",
        to: "Arpora Night Market",
        distanceKm: 31,
        durationMinutes: 65,
        mode: "driving",
      },
    ],
  },
  {
    dayNumber: 5,
    date: "2026-01-20",
    weather: goaWeatherForecast[4],
    slots: [
      createSlot("morning", [
        {
          id: "goa-d5-i1",
          type: "activity",
          itemId: goaActivities[14].id,
          data: goaActivities[14],
          startTime: "07:00",
          endTime: "12:00",
          estimatedCost: 2400,
          currency: "INR",
          orderIndex: 1,
        },
      ]),
      createSlot("afternoon", []),
      createSlot("evening", []),
    ],
    hotel: goaHotels[7],
    totalCost: 25000 + 2400,
    route: [
      {
        from: "Alila Diwa Goa",
        to: "Dudhsagar Falls",
        distanceKm: 72.4,
        durationMinutes: 128,
        mode: "driving",
      },
    ],
  },
];

const makeSimpleTripDays = (
  startDate: string,
  weatherLabel: string,
  cityHotel: Hotel,
  cityActivity: Activity,
): ItineraryDay[] => {
  const days = [0, 1, 2];
  return days.map((offset) => {
    const date = new Date(startDate);
    date.setDate(date.getDate() + offset);
    const isoDate = date.toISOString().split("T")[0];

    return {
      dayNumber: offset + 1,
      date: isoDate,
      weather: {
        date: isoDate,
        tempMax: 24,
        tempMin: 15,
        condition: weatherLabel,
        precipitationChance: 15,
        windSpeed: 10,
        icon: "cloud-sun",
      },
      slots: [
        createSlot("morning", [
          {
            id: `${cityActivity.id}-d${offset + 1}-m`,
            type: "activity",
            itemId: cityActivity.id,
            data: cityActivity,
            startTime: "09:00",
            endTime: "11:00",
            estimatedCost: cityActivity.price,
            currency: cityActivity.currency,
            orderIndex: 1,
          },
        ]),
        createSlot("afternoon", []),
        createSlot("evening", []),
      ],
      hotel: cityHotel,
      totalCost: cityHotel.pricePerNight + cityActivity.price,
      route: [
        {
          from: cityHotel.name,
          to: cityActivity.name,
          distanceKm: 6.2,
          durationMinutes: 20,
          mode: "driving",
        },
      ],
    };
  });
};

const manaliHotel: Hotel = {
  id: "manali-h-1",
  name: "Snowpeak Riverside Lodge",
  city: "Manali",
  country: "India",
  pricePerNight: 5400,
  currency: "INR",
  rating: 4.4,
  stars: 4,
  images: [unsplash("photo-1501785888041-af3ef285b470")],
  amenities: ["Mountain View", "Heater", "Breakfast", "WiFi"],
  lat: 32.2432,
  lng: 77.1892,
  description: "Comfort mountain lodge on the banks of Beas river.",
  externalId: "amd-hotel-snowpeak-riverside",
};

const manaliActivity: Activity = {
  id: "manali-a-1",
  name: "Solang Valley Adventure Park",
  city: "Manali",
  category: "adventure",
  price: 2200,
  currency: "INR",
  duration: 180,
  rating: 4.7,
  image: unsplash("photo-1510798831971-661eb04b3739"),
  description: "Paragliding and snow activities at Solang Valley.",
  lat: 32.3165,
  lng: 77.1572,
  externalId: "otm-solang-adventure",
};

const keralaHotel: Hotel = {
  id: "kerala-h-1",
  name: "Alleppey Backwater Houseboat Stay",
  city: "Kerala",
  country: "India",
  pricePerNight: 8200,
  currency: "INR",
  rating: 4.6,
  stars: 4,
  images: [unsplash("photo-1473625247510-8ceb1760943f")],
  amenities: ["Houseboat", "Meals Included", "Deck View", "Guide"],
  lat: 9.4981,
  lng: 76.3388,
  description: "Classic backwater cruise stay with private cabin.",
  externalId: "amd-hotel-alleppey-houseboat",
};

const keralaActivity: Activity = {
  id: "kerala-a-1",
  name: "Alleppey Backwater Canoe Tour",
  city: "Kerala",
  category: "nature",
  price: 1800,
  currency: "INR",
  duration: 150,
  rating: 4.8,
  image: unsplash("photo-1530789253388-582c481c54b0"),
  description: "Village canal canoe tour with local cuisine tasting.",
  lat: 9.4908,
  lng: 76.3264,
  externalId: "otm-alleppey-canoe",
};

const rajasthanHotel: Hotel = {
  id: "raj-h-1",
  name: "Jaipur Haveli Courtyard",
  city: "Rajasthan",
  country: "India",
  pricePerNight: 6100,
  currency: "INR",
  rating: 4.3,
  stars: 4,
  images: [unsplash("photo-1524492412937-b28074a5d7da")],
  amenities: ["Heritage Stay", "Rooftop Dining", "WiFi", "City Tours"],
  lat: 26.9239,
  lng: 75.8267,
  description: "Heritage-inspired stay near Jaipur old city.",
  externalId: "amd-hotel-jaipur-haveli-courtyard",
};

const rajasthanActivity: Activity = {
  id: "raj-a-1",
  name: "Amber Fort Guided Tour",
  city: "Rajasthan",
  category: "culture",
  price: 900,
  currency: "INR",
  duration: 120,
  rating: 4.6,
  image: unsplash("photo-1599661046289-e31897846e41"),
  description: "Guided architectural and history tour of Amber Fort.",
  lat: 26.9855,
  lng: 75.8513,
  externalId: "otm-amber-fort-tour",
};

const baliHotel: Hotel = {
  id: "bali-h-1",
  name: "Ubud Rice Terrace Resort",
  city: "Bali",
  country: "Indonesia",
  pricePerNight: 14500,
  currency: "INR",
  rating: 4.7,
  stars: 5,
  images: [unsplash("photo-1528127269322-539801943592")],
  amenities: ["Infinity Pool", "Spa", "Rice Field View", "Breakfast"],
  lat: -8.5069,
  lng: 115.2625,
  description: "Serene luxury resort in Ubud valley.",
  externalId: "amd-hotel-ubud-rice-terrace",
};

const baliActivity: Activity = {
  id: "bali-a-1",
  name: "Uluwatu Temple Sunset Tour",
  city: "Bali",
  category: "culture",
  price: 2600,
  currency: "INR",
  duration: 180,
  rating: 4.8,
  image: unsplash("photo-1537996194471-e657df975ab4"),
  description: "Temple cliff tour with Kecak dance performance.",
  lat: -8.8291,
  lng: 115.0849,
  externalId: "otm-uluwatu-tour",
};

const parisHotel: Hotel = {
  id: "paris-h-1",
  name: "Left Bank Boutique Hotel",
  city: "Paris",
  country: "France",
  pricePerNight: 23000,
  currency: "INR",
  rating: 4.6,
  stars: 4,
  images: [unsplash("photo-1502602898657-3e91760cbb34")],
  amenities: ["Metro Access", "Breakfast", "Concierge", "WiFi"],
  lat: 48.8518,
  lng: 2.3394,
  description: "Elegant boutique stay near Seine and museums.",
  externalId: "amd-hotel-left-bank-boutique",
};

const parisActivity: Activity = {
  id: "paris-a-1",
  name: "Louvre and Seine Combo Tour",
  city: "Paris",
  category: "museum",
  price: 4200,
  currency: "INR",
  duration: 210,
  rating: 4.7,
  image: unsplash("photo-1431274172761-fca41d930114"),
  description: "Museum guided entry plus evening river cruise.",
  lat: 48.8606,
  lng: 2.3376,
  externalId: "otm-louvre-seine-combo",
};

export const sampleTrips: Itinerary[] = [
  {
    id: "trip-goa-2026",
    userId: "usr-101",
    title: "Goa Friends Escape",
    destination: "Goa",
    country: "India",
    coverImage: unsplash("photo-1537799943037-f5da89a65689"),
    startDate: "2026-01-16",
    endDate: "2026-01-20",
    totalDays: 5,
    totalBudget: 120000,
    currency: "INR",
    travelers: 4,
    travelStyle: "relaxed",
    days: goaItineraryDays,
    shareToken: "GOA26TRIP01A",
    status: "active",
    collaborators: goaCollaborators,
    createdAt: new Date("2025-12-20T09:00:00.000Z"),
    updatedAt: new Date("2026-01-12T07:30:00.000Z"),
  },
  {
    id: "trip-manali-2025",
    userId: "usr-101",
    title: "Manali Winter Adventure",
    destination: "Manali",
    country: "India",
    coverImage: unsplash("photo-1549880181-56a44cf4a9a5"),
    startDate: "2025-12-10",
    endDate: "2025-12-12",
    totalDays: 3,
    totalBudget: 54000,
    currency: "INR",
    travelers: 2,
    travelStyle: "adventure",
    days: makeSimpleTripDays("2025-12-10", "Cloudy", manaliHotel, manaliActivity),
    shareToken: "MAN25SNOW2X",
    status: "completed",
    collaborators: [goaCollaborators[0], goaCollaborators[2]],
    createdAt: new Date("2025-10-01T08:00:00.000Z"),
    updatedAt: new Date("2025-12-13T18:20:00.000Z"),
  },
  {
    id: "trip-kerala-2025",
    userId: "usr-101",
    title: "Kerala Backwater Calm",
    destination: "Kerala",
    country: "India",
    coverImage: unsplash("photo-1472396961693-142e6e269027"),
    startDate: "2025-09-22",
    endDate: "2025-09-24",
    totalDays: 3,
    totalBudget: 62000,
    currency: "INR",
    travelers: 3,
    travelStyle: "relaxed",
    days: makeSimpleTripDays("2025-09-22", "Humid", keralaHotel, keralaActivity),
    shareToken: "KER25CALM9Q",
    status: "completed",
    collaborators: [goaCollaborators[0], goaCollaborators[1], goaCollaborators[3]],
    createdAt: new Date("2025-07-08T10:40:00.000Z"),
    updatedAt: new Date("2025-09-25T09:20:00.000Z"),
  },
  {
    id: "trip-rajasthan-2026",
    userId: "usr-101",
    title: "Rajasthan Heritage Circuit",
    destination: "Rajasthan",
    country: "India",
    coverImage: unsplash("photo-1598091383021-15ddea10925d"),
    startDate: "2026-03-25",
    endDate: "2026-03-27",
    totalDays: 3,
    totalBudget: 70000,
    currency: "INR",
    travelers: 2,
    travelStyle: "cultural",
    days: makeSimpleTripDays("2026-03-25", "Sunny", rajasthanHotel, rajasthanActivity),
    shareToken: "RAJ26FORT8K",
    status: "draft",
    collaborators: [goaCollaborators[0], goaCollaborators[1]],
    createdAt: new Date("2026-03-01T12:30:00.000Z"),
    updatedAt: new Date("2026-03-11T14:30:00.000Z"),
  },
  {
    id: "trip-bali-2026",
    userId: "usr-101",
    title: "Bali Couple Getaway",
    destination: "Bali",
    country: "Indonesia",
    coverImage: unsplash("photo-1518548419970-58e3b4079ab2"),
    startDate: "2026-06-08",
    endDate: "2026-06-10",
    totalDays: 3,
    totalBudget: 150000,
    currency: "INR",
    travelers: 2,
    travelStyle: "luxury",
    days: makeSimpleTripDays("2026-06-08", "Sunny", baliHotel, baliActivity),
    shareToken: "BAL26WAVE6R",
    status: "draft",
    collaborators: [goaCollaborators[0]],
    createdAt: new Date("2026-02-14T08:45:00.000Z"),
    updatedAt: new Date("2026-03-10T16:00:00.000Z"),
  },
  {
    id: "trip-paris-2026",
    userId: "usr-101",
    title: "Paris Art Week",
    destination: "Paris",
    country: "France",
    coverImage: unsplash("photo-1499856871958-5b9627545d1a"),
    startDate: "2026-09-14",
    endDate: "2026-09-16",
    totalDays: 3,
    totalBudget: 190000,
    currency: "INR",
    travelers: 2,
    travelStyle: "cultural",
    days: makeSimpleTripDays("2026-09-14", "Mild", parisHotel, parisActivity),
    shareToken: "PAR26ART3MZ",
    status: "draft",
    collaborators: [goaCollaborators[0], goaCollaborators[3]],
    createdAt: new Date("2026-03-03T09:10:00.000Z"),
    updatedAt: new Date("2026-03-12T06:40:00.000Z"),
  },
];

export const goaBudgetBreakdown: BudgetBreakdown = {
  accommodation: 47000,
  activities: 13500,
  food: 18000,
  transport: 9000,
  events: 8200,
  total: 95700,
  currency: "INR",
};

export const goaCityInfo: CityInfo = {
  name: "Goa",
  country: "India",
  safetyScore: 7.8,
  costOfLiving: 6.2,
  qualityOfLife: 8.4,
  currency: "INR",
  timezone: "Asia/Kolkata",
  language: "Konkani, English, Hindi",
};

export const sampleBookings: Booking[] = [
  {
    id: "booking-1",
    userId: "usr-101",
    itineraryId: "trip-goa-2026",
    itemType: "hotel",
    itemData: goaHotels[2],
    amount: 19200,
    currency: "INR",
    status: "confirmed",
    stripeSessionId: "cs_test_a1B2c3D4confirmed",
    createdAt: new Date("2026-01-08T09:12:00.000Z"),
  },
  {
    id: "booking-2",
    userId: "usr-102",
    itineraryId: "trip-goa-2026",
    itemType: "event",
    itemData: goaEvents[0],
    amount: 4500,
    currency: "INR",
    status: "pending",
    stripeSessionId: "cs_test_e5F6g7H8pending",
    createdAt: new Date("2026-01-09T15:30:00.000Z"),
  },
  {
    id: "booking-3",
    userId: "usr-104",
    itineraryId: "trip-goa-2026",
    itemType: "activity",
    itemData: goaActivities[14],
    amount: 2400,
    currency: "INR",
    status: "cancelled",
    stripeSessionId: "cs_test_i9J0k1L2cancelled",
    createdAt: new Date("2026-01-05T11:00:00.000Z"),
  },
];

export const tripStats: TripStats = {
  totalTrips: 6,
  countries: 3,
  totalSpent: 482500,
  avgTripDuration: 3.3,
  mostVisitedCity: "Goa",
  totalDistance: 9240,
};

export const popularDestinations: PopularDestination[] = [
  {
    name: "Goa",
    country: "India",
    avgBudget: 85000,
    bestMonths: "Nov-Feb",
    flightHoursFromIndia: 2,
    coverImage: unsplash("photo-1537799943037-f5da89a65689"),
  },
  {
    name: "Manali",
    country: "India",
    avgBudget: 52000,
    bestMonths: "Oct-Feb",
    flightHoursFromIndia: 1.5,
    coverImage: unsplash("photo-1549880181-56a44cf4a9a5"),
  },
  {
    name: "Bali",
    country: "Indonesia",
    avgBudget: 155000,
    bestMonths: "Apr-Oct",
    flightHoursFromIndia: 8,
    coverImage: unsplash("photo-1518548419970-58e3b4079ab2"),
  },
  {
    name: "Paris",
    country: "France",
    avgBudget: 210000,
    bestMonths: "Apr-Jun",
    flightHoursFromIndia: 9,
    coverImage: unsplash("photo-1499856871958-5b9627545d1a"),
  },
  {
    name: "Tokyo",
    country: "Japan",
    avgBudget: 220000,
    bestMonths: "Mar-May",
    flightHoursFromIndia: 8,
    coverImage: unsplash("photo-1540959733332-eab4deabeeaf"),
  },
  {
    name: "Dubai",
    country: "UAE",
    avgBudget: 140000,
    bestMonths: "Nov-Mar",
    flightHoursFromIndia: 3.5,
    coverImage: unsplash("photo-1512453979798-5ea266f8880c"),
  },
];
